// Compiles src/engine/wasm/kernels.wat into src/engine/wasm/kernels.ts (committed):
//
//   npm run build:wasm
//
// The bytes are written as a Uint8Array literal so the engine needs no fetch,
// no base64 and no DOM types: it runs unchanged in Node tests, the worker and
// the static build. kernels.test.ts checks the committed bytes are current.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileKernels } from './wasm.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const wat = readFileSync(resolve(root, 'src/engine/wasm/kernels.wat'), 'utf8');
const bytes = await compileKernels(wat);
const lines: string[] = [];
for (let i = 0; i < bytes.length; i += 24)
  lines.push(`  ${Array.from(bytes.subarray(i, i + 24)).join(', ')},`);
const out = `// Generated by scripts/build-wasm.ts from kernels.wat: do not edit. Run \`npm run build:wasm\`.
// prettier-ignore
export const KERNELS_WASM = new Uint8Array([
${lines.join('\n')}
]);
`;
writeFileSync(resolve(root, 'src/engine/wasm/kernels.ts'), out);
console.log(`kernels.wasm: ${bytes.length} bytes`);
